---

- name: Set up a local isolated vm for using ueransim
  hosts: ['ueransim']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes

  tasks:
    # NOTE: All commented parts could be necessary, but currently seem to do nothing
    #       Commented out for testing performance
  
    # - name: Remove old cmake
    #   apt:
    #     name: cmake
    #     state: absent
    #     purge: yes

    - name: Install dependencies - g++
      apt:
        name: g++
        state: present

    - name: Install dependencies - software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Install dependencies - lsb-release
      apt:
        name: lsb-release
        state: present
        update_cache: yes

    - name: Add kitware key
      apt_key:
        url: "https://apt.kitware.com/keys/kitware-archive-latest.asc"
        state: present

    - name: Add kitware repos
      apt_repository:
        repo: "deb https://apt.kitware.com/ubuntu/ bionic main"
        state: present
        update_cache: yes

    - name: Install cmake
      apt:
        name: cmake
        state: present

    - name: Clone UERANSIM
      git:
        repo: https://github.com/aligungr/UERANSIM
        dest: /home/vagrant/UERANSIM
    
    # Takes a long time
    - name: Make UERANSIM
      make:
        chdir: /home/vagrant/UERANSIM