---

- name: Set up a local isolated vm for using ueransim
  hosts: ['ueransim']
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes

  tasks:
    - name: Install dependencies - g++
      apt:
        name: g++
        state: present

    - name: Install dependencies - libsctp-dev
      apt:
        name: libsctp-dev
        state: present
        update_cache: yes

    - name: Install dependencies - lksctp-tools
      apt:
        name: lksctp-tools
        state: present

    - name: Install dependencies - software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Install dependencies - lsb-release
      apt:
        name: lsb-release
        state: present
        update_cache: yes

    - name: Add kitware key
      apt_key:
        url: "https://apt.kitware.com/keys/kitware-archive-latest.asc"
        state: present

    - name: Add kitware repos
      apt_repository:
        repo: "deb https://apt.kitware.com/ubuntu/ bionic main"
        state: present
        update_cache: yes

    - name: Install cmake
      apt:
        name: cmake
        state: present

    - name: Clone UERANSIM
      git:
        repo: https://github.com/aligungr/UERANSIM
        dest: /home/vagrant/UERANSIM

    - name: Make UERANSIM
      make:
        chdir: /home/vagrant/UERANSIM

    - name: Copy configs over
      copy:
        src: "../../configs/"
        dest: "/home/vagrant/configs"
        remote_src: no